<?= $this->extend('layouts/master_admin_layout') ?> // Assumes you have a layout file

<?= $this->section('content') ?>

    <div class="container mt-4">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h1>Manage Access Codes</h1>

            <form action="<?= site_url('/master-admin/access-codes/generate') ?>" method="post">
                <?= csrf_field() ?>
                <button type="submit" class="btn btn-primary">Generate New Code</button>
            </form>
        </div>

        <?php if (session()->getFlashdata('message')): ?>
            <div class="alert alert-success"><?= session()->getFlashdata('message') ?></div>
        <?php elseif (session()->getFlashdata('error')): ?>
            <div class="alert alert-danger"><?= session()->getFlashdata('error') ?></div>
        <?php endif; ?>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Generated Codes</h5>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Access Code</th>
                        <th scope="col">Status</th>
                        <th scope="col">Generated By</th>
                        <th scope="col">Used By (Instructor)</th>
                        <th scope="col">Date Generated</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($codes)): ?>
                        <?php foreach ($codes as $index => $code): ?>
                            <tr>
                                <th scope="row"><?= $index + 1 ?></th>
                                <td><strong><?= esc($code['code']) ?></strong></td>
                                <td>
                                    <?php if ($code['is_used']): ?>
                                        <span class="badge bg-success">Used</span>
                                    <?php else: ?>
                                        <span class="badge bg-warning text-dark">Not Used</span>
                                    <?php endif; ?>
                                </td>
                                <td><?= esc($code['creator_username'] ?? 'N/A') ?></td>
                                <td><?= esc($code['user_username'] ?? 'N/A') ?></td>
                                <td><?= date('F j, Y, g:i a', strtotime($code['created_at'])) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" class="text-center">No access codes found. Generate one to get started!</td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<?= $this->endSection() ?>